// The TARDIS crew across 60+ years. Curated to the ones who actually
// piloted with the Doctor for a sustained run — passers-by like
// Sarah Jane's nephew Luke and one-shot guests like Astrid Peth aren't
// here. Wikidata is the source of truth; this is the demo subset.

export type Companion = {
  name: string;
  actor: string;
  doctors: string[];           // Doctor numbers they travelled with
  era: string;                 // "1963–1965"
  yearStart: number;
  yearEnd: number;
  origin: string;              // where/when they came from
  fate: string;                // how they left
  blurb: string;
  iconic: boolean;             // top tier — get bigger card
};

export const companions: Companion[] = [
  // ─────────── Classic era ───────────
  {
    name: "Susan Foreman", actor: "Carole Ann Ford", doctors: ["1"], era: "1963–1964",
    yearStart: 1963, yearEnd: 1964,
    origin: "The Doctor's granddaughter, hiding in 1963 London.",
    fate: "Doctor locked her out of the TARDIS so she'd stay with David Campbell on 22nd-century Earth. \"One day, I shall come back.\" He didn't.",
    blurb: "The original. Started the show. Time Lord by birth, possibly. The lineage question is the show's oldest thread.",
    iconic: true,
  },
  {
    name: "Barbara Wright", actor: "Jacqueline Hill", doctors: ["1"], era: "1963–1965",
    yearStart: 1963, yearEnd: 1965,
    origin: "Coal Hill School history teacher who followed Susan home.",
    fate: "Home to 1965 London with Ian, via a Dalek time machine.",
    blurb: "Half of the original kidnapping. The reason the Doctor became someone you'd actually want to travel with — she civilised him.",
    iconic: false,
  },
  {
    name: "Ian Chesterton", actor: "William Russell", doctors: ["1"], era: "1963–1965",
    yearStart: 1963, yearEnd: 1965,
    origin: "Coal Hill School science teacher; Barbara's colleague.",
    fate: "Same Dalek time machine, same 1965 London. Later: Chairman of the Governors of Coal Hill, knighted in 2022.",
    blurb: "Knight of Jaffa. Hit a Voord with a rock once. Older than the show itself; saw Ten in the school in 2022.",
    iconic: false,
  },
  {
    name: "Vicki", actor: "Maureen O'Brien", doctors: ["1"], era: "1965",
    yearStart: 1965, yearEnd: 1965,
    origin: "Crashed colonist child on Dido.",
    fate: "Left to be Cressida in the fall of Troy.",
    blurb: "Soft replacement for Susan. Adopted by the historical past.",
    iconic: false,
  },
  {
    name: "Steven Taylor", actor: "Peter Purves", doctors: ["1"], era: "1965–1966",
    yearStart: 1965, yearEnd: 1966,
    origin: "Crashed space pilot held captive by the Mechonoids.",
    fate: "Stayed to rule the Elders / Savages.",
    blurb: "Hardest-working Doctor Who Magazine companion to track on TV — half his stories are missing.",
    iconic: false,
  },
  {
    name: "Jamie McCrimmon", actor: "Frazer Hines", doctors: ["2"], era: "1966–1969",
    yearStart: 1966, yearEnd: 1969,
    origin: "Highlander piper, Battle of Culloden 1746.",
    fate: "Time Lords wiped his memory and sent him back to Culloden.",
    blurb: "Longest-serving classic-era companion. Kilt. Dirk. \"Creature!\" at anything blue. Half of the Two-and-Jamie duo that defined the era.",
    iconic: true,
  },
  {
    name: "Zoe Heriot", actor: "Wendy Padbury", doctors: ["2"], era: "1968–1969",
    yearStart: 1968, yearEnd: 1969,
    origin: "Astrophysicist on the Wheel in Space, 21st century.",
    fate: "Memory-wiped by the Time Lords, sent home.",
    blurb: "Genius-IQ companion before Romana. Glittery catsuit; remembers being clever, can't remember the Doctor.",
    iconic: false,
  },
  {
    name: "Liz Shaw", actor: "Caroline John", doctors: ["3"], era: "1970",
    yearStart: 1970, yearEnd: 1970,
    origin: "Cambridge scientist seconded to UNIT.",
    fate: "Went back to Cambridge. Bored of being handed test tubes.",
    blurb: "First UNIT-era companion. Treated as a peer, which is rare.",
    iconic: false,
  },
  {
    name: "Jo Grant", actor: "Katy Manning", doctors: ["3"], era: "1971–1973",
    yearStart: 1971, yearEnd: 1973,
    origin: "UNIT secretary who failed her A-levels and was assigned to the Doctor anyway.",
    fate: "Married Professor Cliff Jones and went up the Amazon.",
    blurb: "Cosy, screamy, kind. Sarah Jane Adventures brought her back as a hippie travelling grandmother who has been around the world twice on her own.",
    iconic: false,
  },
  {
    name: "Sarah Jane Smith", actor: "Elisabeth Sladen", doctors: ["3", "4", "10", "11"], era: "1973–1976, 2006, 2010",
    yearStart: 1973, yearEnd: 2011,
    origin: "Journalist who sneaked into UNIT looking for a story.",
    fate: "Dropped off in \"Croydon\" (Aberdeen). Found again in School Reunion. Got her own spin-off until 2011.",
    blurb: "The single most beloved classic companion. The reason \"School Reunion\" makes adults cry. K-9 mk III, the sonic lipstick, the attic full of aliens. Sladen died in 2011 and the show has never replaced her.",
    iconic: true,
  },
  {
    name: "Harry Sullivan", actor: "Ian Marter", doctors: ["4"], era: "1974–1975",
    yearStart: 1974, yearEnd: 1975,
    origin: "Naval surgeon at UNIT.",
    fate: "Stayed on Earth after Terror of the Zygons.",
    blurb: "\"Imbecile\" (affectionate). Last male UNIT-era companion until Wilf.",
    iconic: false,
  },
  {
    name: "Leela", actor: "Louise Jameson", doctors: ["4"], era: "1977–1978",
    yearStart: 1977, yearEnd: 1978,
    origin: "Sevateem warrior on a far-future colony world.",
    fate: "Stayed on Gallifrey with Andred. (Big Finish has many opinions.)",
    blurb: "Bare-legged knife-thrower. The Doctor tries (and fails) to teach her My Fair Lady. Big Finish made her one of the most-recorded companions ever.",
    iconic: false,
  },
  {
    name: "Romana I", actor: "Mary Tamm", doctors: ["4"], era: "1978–1979",
    yearStart: 1978, yearEnd: 1979,
    origin: "Time Lady from Gallifrey, assigned by the White Guardian.",
    fate: "Regenerated.",
    blurb: "Posh, brilliant, Doctor's first peer. Key to Time arc.",
    iconic: false,
  },
  {
    name: "Romana II", actor: "Lalla Ward", doctors: ["4"], era: "1979–1981",
    yearStart: 1979, yearEnd: 1981,
    origin: "Same Time Lady, after a regeneration that picked a body like Princess Astra's.",
    fate: "Stayed in E-Space to free the Tharils.",
    blurb: "The famous one. Long scarf to Four's long scarf; intellectual partner. Tom and Lalla were married briefly in real life.",
    iconic: true,
  },
  {
    name: "K-9", actor: "John Leeson (voice)", doctors: ["4", "10"], era: "1977–1981, 2006",
    yearStart: 1977, yearEnd: 2006,
    origin: "Built in 5000 AD by Professor Marius.",
    fate: "Multiple. There are at least four K-9s. The Doctor builds Sarah Jane a new one in School Reunion.",
    blurb: "Robot dog. Laser nose. \"Affirmative, master.\" The Sarah Jane Adventures gave him a flat that he flies away from.",
    iconic: true,
  },
  {
    name: "Adric", actor: "Matthew Waterhouse", doctors: ["4", "5"], era: "1980–1982",
    yearStart: 1980, yearEnd: 1982,
    origin: "Alzarian boy from E-Space.",
    fate: "Died crashing a Cyber-freighter into prehistoric Earth (it became the Yucatán impact). The show ran the credits in silence.",
    blurb: "Disliked at the time, mourned now. The companion who actually died.",
    iconic: false,
  },
  {
    name: "Nyssa", actor: "Sarah Sutton", doctors: ["4", "5"], era: "1981–1983",
    yearStart: 1981, yearEnd: 1983,
    origin: "Princess of Traken; her father's body was stolen by the Master.",
    fate: "Stayed on Terminus to cure Lazar's Disease.",
    blurb: "Quietest companion. Big Finish made her the moral centre of Five's TARDIS team.",
    iconic: false,
  },
  {
    name: "Tegan Jovanka", actor: "Janet Fielding", doctors: ["4", "5"], era: "1981–1984, 2022",
    yearStart: 1981, yearEnd: 2022,
    origin: "Australian air stewardess on her first day, took the wrong door.",
    fate: "Left in tears after Resurrection of the Daleks. Came back in Power of the Doctor with cancer she's beating.",
    blurb: "\"Brave heart, Tegan.\" Talked back at the Doctor more than any other classic companion. Power of the Doctor brought her, Ace, Jo and Mel back at once and that scene at the support group reduced fanbases to a puddle.",
    iconic: true,
  },
  {
    name: "Turlough", actor: "Mark Strickson", doctors: ["5"], era: "1983–1984",
    yearStart: 1983, yearEnd: 1984,
    origin: "Trion political exile hiding at an English public school.",
    fate: "Went home to Trion when the political prisoners were amnestied.",
    blurb: "Tried to kill the Doctor in his first three serials. Anti-companion turned ally.",
    iconic: false,
  },
  {
    name: "Peri Brown", actor: "Nicola Bryant", doctors: ["5", "6"], era: "1984–1986",
    yearStart: 1984, yearEnd: 1986,
    origin: "American botany student on holiday in Lanzarote.",
    fate: "Trial of a Time Lord said she died; revised mid-trial to say she married King Yrcanos and lived. Big Finish unmoored.",
    blurb: "Caves of Androzani is Five's regeneration. Six grabbed her by the throat in his first scene; took six episodes to recover.",
    iconic: false,
  },
  {
    name: "Mel Bush", actor: "Bonnie Langford", doctors: ["6", "7"], era: "1986–1987, 2022–2024",
    yearStart: 1986, yearEnd: 2024,
    origin: "Computer programmer from Pease Pottage.",
    fate: "Wandered off with Sabalom Glitz in Dragonfire. Brought back in Power of the Doctor and now Fifteen's UNIT crew (Empire of Death).",
    blurb: "Carrot juice, scream, the show's most arbitrary entrance — written in mid-arc. Power of the Doctor showed her surprisingly devastating as a Cyber-converted hostage of the Master.",
    iconic: false,
  },
  {
    name: "Ace", actor: "Sophie Aldred", doctors: ["7"], era: "1987–1989, 2022",
    yearStart: 1987, yearEnd: 2022,
    origin: "Perivale teenager flung to Iceworld by a time storm she half-caused.",
    fate: "Show ended mid-arc; novels send her to Gallifrey to train. Power of the Doctor: ex-companion in a leather jacket falling out of a CSO sky.",
    blurb: "Nitro-9 in the rucksack, baseball bat the size of a Dalek's eyestalk. Last classic companion. Power of the Doctor: \"Hello, Professor.\"",
    iconic: true,
  },
  {
    name: "Grace Holloway", actor: "Daphne Ashbrook", doctors: ["8"], era: "1996",
    yearStart: 1996, yearEnd: 1996,
    origin: "San Francisco cardiologist on New Year's Eve 1999.",
    fate: "Stayed.",
    blurb: "The TV Movie companion. Kissed Eight; doesn't count toward modern continuity (or does, depending who you ask).",
    iconic: false,
  },

  // ─────────── Modern era ───────────
  {
    name: "Rose Tyler", actor: "Billie Piper", doctors: ["9", "10", "Meta-Crisis"], era: "2005–2008",
    yearStart: 2005, yearEnd: 2008,
    origin: "Powell Estate shop girl, 19, mum on the council.",
    fate: "Trapped in Pete's World twice. Got the Meta-Crisis Doctor as a parting gift.",
    blurb: "The arc that brought the show back. Bad Wolf graffiti across spacetime, looked into the heart of the TARDIS and lit it up. \"Rose Tyler—\"",
    iconic: true,
  },
  {
    name: "Mickey Smith", actor: "Noel Clarke", doctors: ["9", "10"], era: "2005–2008",
    yearStart: 2005, yearEnd: 2008,
    origin: "Powell Estate, Rose's boyfriend, eaten by a wheelie bin in his first episode.",
    fate: "Married Martha. Last seen fighting Sontarans in End of Time.",
    blurb: "Promoted from tin dog to people's resistance against Cybus Industries.",
    iconic: false,
  },
  {
    name: "Captain Jack Harkness", actor: "John Barrowman", doctors: ["9", "10"], era: "2005–2010",
    yearStart: 2005, yearEnd: 2010,
    origin: "51st-century Time Agent / con artist, Boeshane Peninsula.",
    fate: "Made immortal by Rose-Bad-Wolf. Runs Torchwood. Will become the Face of Boe.",
    blurb: "Pansexual time-traveling con-man who can't die. Spun off Torchwood. The Face of Boe theory is canon by Last of the Time Lords; Russell T Davies confirmed it.",
    iconic: true,
  },
  {
    name: "Martha Jones", actor: "Freema Agyeman", doctors: ["10"], era: "2007–2008",
    yearStart: 2007, yearEnd: 2008,
    origin: "Royal Hope medical student, North London family.",
    fate: "Walked away with her dignity intact (more than the Doctor ever offered Rose). Married Mickey. UNIT doctor.",
    blurb: "The companion who saved the world walking. Last of the Time Lords: a year telling the Doctor's story across an Earth conquered by the Master. Underrated forever.",
    iconic: false,
  },
  {
    name: "Donna Noble", actor: "Catherine Tate", doctors: ["10", "14"], era: "2008, 2023",
    yearStart: 2008, yearEnd: 2023,
    origin: "Temp from Chiswick, on her wedding day.",
    fate: "DoctorDonna metacrisis burned her up; memory wiped. 2023 returned — her daughter Rose let it out safely.",
    blurb: "Best mate, not love interest. The DoctorDonna saved the universe and then had to forget. Fourteen's whole arc was undoing this.",
    iconic: true,
  },
  {
    name: "Wilfred Mott", actor: "Bernard Cribbins", doctors: ["10", "14"], era: "2009–2010, 2023",
    yearStart: 2009, yearEnd: 2023,
    origin: "Donna's grandad. Newspaper seller.",
    fate: "Four knocks. Took Ten's regeneration in End of Time. Returned for Wild Blue Yonder before Cribbins's death.",
    blurb: "The salute. The tears. The four knocks. Cribbins was 91 when he came back; his final scene with Tennant is the cleanest goodbye in the franchise.",
    iconic: true,
  },
  {
    name: "Amy Pond", actor: "Karen Gillan", doctors: ["11"], era: "2010–2012",
    yearStart: 2010, yearEnd: 2012,
    origin: "Leadworth, age 7, raggedy man comes through her shed.",
    fate: "Touched by a Weeping Angel into 1938 New York.",
    blurb: "Waited 12 years. Married Rory. Had a daughter who turned into River Song. Most Steven Moffat companion possible.",
    iconic: true,
  },
  {
    name: "Rory Williams", actor: "Arthur Darvill", doctors: ["11"], era: "2010–2012",
    yearStart: 2010, yearEnd: 2012,
    origin: "Leadworth nurse, Amy's fiancé.",
    fate: "Same Angel, same New York. Lived a full life and died of old age.",
    blurb: "The Last Centurion: Auton duplicate guarding the Pandorica for two thousand years. Died so many times it became a running gag.",
    iconic: true,
  },
  {
    name: "River Song", actor: "Alex Kingston", doctors: ["10", "11", "12"], era: "2008–2015",
    yearStart: 2008, yearEnd: 2015,
    origin: "Melody Pond. Daughter of Amy and Rory, conceived in the TARDIS, raised by the Silence to kill the Doctor.",
    fate: "Library hard drive in Forest of the Dead — first met him, last for her. Husbands of River Song: their last night, 24 years long.",
    blurb: "Their timelines run opposite. \"Hello, Sweetie.\" Wife of the Doctor. Killed the Doctor. Met him as a child without knowing. The most Moffat thing ever filmed.",
    iconic: true,
  },
  {
    name: "Clara Oswald", actor: "Jenna Coleman", doctors: ["11", "12"], era: "2012–2015",
    yearStart: 2012, yearEnd: 2015,
    origin: "Coal Hill School English teacher. Also: scattered through the Doctor's timeline by stepping into his timestream.",
    fate: "Heaven Sent / Hell Bent: died facing the Quantum Shade, lifted out between heartbeats by Twelve. Now travels with Ashildr in a TARDIS \"the long way round to Gallifrey.\"",
    blurb: "Impossible Girl. The Doctor pulled the universe apart to save her; she made him forget her to save him. Has her own TARDIS now.",
    iconic: true,
  },
  {
    name: "Danny Pink", actor: "Samuel Anderson", doctors: ["12"], era: "2014",
    yearStart: 2014, yearEnd: 2014,
    origin: "Coal Hill maths teacher, ex-soldier. Clara's boyfriend.",
    fate: "Hit by a car. Cyber-converted. Gave his afterlife to bring back the boy he killed in Iraq.",
    blurb: "Soldier vs Officer. The whole season's argument.",
    iconic: false,
  },
  {
    name: "Bill Potts", actor: "Pearl Mackie", doctors: ["12"], era: "2017",
    yearStart: 2017, yearEnd: 2017,
    origin: "University canteen worker; the Doctor was tutoring her on the sly.",
    fate: "Cyber-converted on Floor 1056; rescued by Heather and the puddle as immortal star-stuff.",
    blurb: "First openly gay companion. Twelve at his most teacherly. \"I don't think of you that way.\"",
    iconic: true,
  },
  {
    name: "Nardole", actor: "Matt Lucas", doctors: ["12"], era: "2015–2017",
    yearStart: 2015, yearEnd: 2017,
    origin: "Husbands of River Song — a head on a stick.",
    fate: "Stayed on the Mondasian colony ship to guide the survivors.",
    blurb: "Comic-relief carer River asked to keep an eye on the Doctor. Bigger heart than the credits suggest.",
    iconic: false,
  },
  {
    name: "Yasmin Khan", actor: "Mandip Gill", doctors: ["13"], era: "2018–2022",
    yearStart: 2018, yearEnd: 2022,
    origin: "Sheffield police officer, second-generation British-Pakistani.",
    fate: "Walked away in Power of the Doctor after declining to keep waiting.",
    blurb: "In love with the Doctor; the show finally said so in Eve of the Daleks. The Doctor didn't say it back. Painful, kind, well-written by the end.",
    iconic: true,
  },
  {
    name: "Ryan Sinclair", actor: "Tosin Cole", doctors: ["13"], era: "2018–2020",
    yearStart: 2018, yearEnd: 2020,
    origin: "Sheffield apprentice mechanic with dyspraxia.",
    fate: "Stayed home to help Yaz's grandfather and look after Earth.",
    blurb: "The bike-riding arc across a season. First main companion with dyspraxia.",
    iconic: false,
  },
  {
    name: "Graham O'Brien", actor: "Bradley Walsh", doctors: ["13"], era: "2018–2020",
    yearStart: 2018, yearEnd: 2020,
    origin: "Sheffield. Retired bus driver. Cancer survivor. Married to Ryan's grandmother Grace.",
    fate: "Stayed with Ryan.",
    blurb: "Granddad-coded warmth. The whole reason the Thirteen TARDIS team had a beating heart.",
    iconic: true,
  },
  {
    name: "Dan Lewis", actor: "John Bishop", doctors: ["13"], era: "2021–2022",
    yearStart: 2021, yearEnd: 2022,
    origin: "Liverpool food-bank volunteer.",
    fate: "Walked away after the Sea Devils, in love and unable to keep up the cosmic pace.",
    blurb: "Scouse warmth, brought in for Flux. Half-romance with Diane never quite landed before the show changed showrunners.",
    iconic: false,
  },
  {
    name: "Ruby Sunday", actor: "Millie Gibson", doctors: ["14", "15"], era: "2023–2024",
    yearStart: 2023, yearEnd: 2024,
    origin: "Abandoned on the steps of a church on Ruby Road one snowy Christmas Eve, 2004.",
    fate: "Found her birth mother. Stayed on Earth — but only just.",
    blurb: "The snow follows her. Memory is the season's mystery. Whole season hinged on whether her mother was a goddess, a ghost or a 17-year-old in the rain. (Spoiler: door three.)",
    iconic: true,
  },
  {
    name: "Belinda Chandra", actor: "Varada Sethu", doctors: ["15"], era: "2025",
    yearStart: 2025, yearEnd: 2025,
    origin: "Croydon nurse who only wants to go home.",
    fate: "Currently travelling.",
    blurb: "Doesn't want to be on the TARDIS. The Doctor keeps not landing on her front step. Whole season is the slow burn of two people learning to like each other.",
    iconic: true,
  },
  {
    name: "Kate Lethbridge-Stewart", actor: "Jemma Redgrave", doctors: ["11", "12", "13", "14", "15"], era: "2012–present",
    yearStart: 2012, yearEnd: 2026,
    origin: "Daughter of Brigadier Alistair Gordon Lethbridge-Stewart. Took over UNIT.",
    fate: "Active. Survived Cyber-conversion in Power of the Doctor.",
    blurb: "The continuity bridge. UNIT's anchor across the modern run. Five Doctors in, still here.",
    iconic: false,
  },
  {
    name: "Brigadier Alistair Gordon Lethbridge-Stewart", actor: "Nicholas Courtney", doctors: ["2", "3", "4", "5", "6", "7", "11"], era: "1968–2011",
    yearStart: 1968, yearEnd: 2011,
    origin: "British Army; founded UNIT.",
    fate: "Died off-screen during Eleven's run (\"Wind of Change\"). Returned as a Cyberman to salute Twelve in Death in Heaven.",
    blurb: "\"Five rounds rapid.\" The single longest-running supporting character in TV science fiction. Five-Doctor stories felt complete because he was in them.",
    iconic: true,
  },
];
