// Curated list of stories. Includes classic serials (counted as one entry
// regardless of part count) and modern episodes. Heavily skewed toward
// the canonical "where you start" list and the load-bearing arc episodes.
// Wikidata + TARDIS wiki backs the full ingest; this is the demo subset.

export type Episode = {
  title: string;
  doctor: string;             // primary Doctor number
  year: number;
  format: "serial" | "episode" | "special" | "minisode";
  partsOrLength?: string;     // "4 parts" or "62 min"
  monsters?: string[];        // names that link into monsters.ts
  companions?: string[];      // names that link into companions.ts
  significance: string;       // why it matters
  blurb: string;
  iconic: boolean;
};

export const episodes: Episode[] = [
  // ─── Hartnell era ───
  { title: "An Unearthly Child", doctor: "1", year: 1963, format: "serial", partsOrLength: "4 parts",
    companions: ["Susan Foreman", "Barbara Wright", "Ian Chesterton"],
    significance: "The first episode. The TARDIS leaves the junkyard at 76 Totter's Lane.",
    blurb: "Two teachers follow their student home. The student is alien. The grandfather is older.", iconic: true },
  { title: "The Daleks", doctor: "1", year: 1963, format: "serial", partsOrLength: "7 parts",
    monsters: ["Daleks"],
    significance: "Daleks debut, in episode two. The show was made.",
    blurb: "Petrified jungle of Skaro. \"EX-TER-MIN-ATE\" enters the language.", iconic: true },
  { title: "The Aztecs", doctor: "1", year: 1964, format: "serial", partsOrLength: "4 parts",
    significance: "Establishes \"You can't change history. Not one line.\"",
    blurb: "Barbara is mistaken for a goddess. She tries to end human sacrifice. She fails.", iconic: false },
  { title: "The Tenth Planet", doctor: "1", year: 1966, format: "serial", partsOrLength: "4 parts",
    monsters: ["Cybermen"],
    significance: "First regeneration. First Cybermen.",
    blurb: "Mondas, Earth's lost twin, arrives. Hartnell collapses at the console.", iconic: true },

  // ─── Troughton era ───
  { title: "The Tomb of the Cybermen", doctor: "2", year: 1967, format: "serial", partsOrLength: "4 parts",
    monsters: ["Cybermen"],
    significance: "Patrick Troughton at his best; sole surviving Troughton Cyber-serial.",
    blurb: "An archaeological dig on Telos. The Cybermen wake.", iconic: false },
  { title: "The War Games", doctor: "2", year: 1969, format: "serial", partsOrLength: "10 parts",
    significance: "Time Lords named for the first time. The Doctor is tried by his own people.",
    blurb: "Soldiers from a dozen wars fighting on one alien world. The Doctor calls Gallifrey for help; they answer.", iconic: true },

  // ─── Pertwee era ───
  { title: "Spearhead from Space", doctor: "3", year: 1970, format: "serial", partsOrLength: "4 parts",
    monsters: [],
    significance: "First colour serial. UNIT era proper.",
    blurb: "Autons in shop windows; plastic daffodils kill. The Doctor wakes up in hospital with a new face.", iconic: false },
  { title: "Inferno", doctor: "3", year: 1970, format: "serial", partsOrLength: "7 parts",
    significance: "Parallel-Earth fascism episode.",
    blurb: "A drilling project breaks through to magma. In the parallel world, the Brigade Leader has an eyepatch and a Hitler moustache.", iconic: false },
  { title: "Terror of the Autons", doctor: "3", year: 1971, format: "serial", partsOrLength: "4 parts",
    monsters: ["The Master / Missy"],
    significance: "The Master's first appearance.",
    blurb: "Roger Delgado walks on screen with a goatee and the show finds its second-best villain.", iconic: true },

  // ─── Tom Baker era ───
  { title: "Genesis of the Daleks", doctor: "4", year: 1975, format: "serial", partsOrLength: "6 parts",
    monsters: ["Daleks", "Davros"],
    companions: ["Sarah Jane Smith", "Harry Sullivan"],
    significance: "Origin of the Daleks. Davros debut. \"Have I that right?\"",
    blurb: "Time Lords send the Doctor back to Skaro to abort the Daleks at birth. He holds two wires together and can't do it.", iconic: true },
  { title: "Pyramids of Mars", doctor: "4", year: 1975, format: "serial", partsOrLength: "4 parts",
    monsters: ["Sutekh"],
    companions: ["Sarah Jane Smith"],
    significance: "Best classic-era horror tone. Setup paid off 49 years later in Empire of Death.",
    blurb: "Edwardian England. A mummy stalks the manor. Sutekh the Destroyer is chained beneath the Pyramid of Mars.", iconic: true },
  { title: "The Deadly Assassin", doctor: "4", year: 1976, format: "serial", partsOrLength: "4 parts",
    monsters: ["The Master / Missy"],
    significance: "First Gallifrey serial without companions. Cemented Time Lord lore.",
    blurb: "The Doctor is framed for the President's assassination. The Master returns as a decayed husk.", iconic: false },
  { title: "City of Death", doctor: "4", year: 1979, format: "serial", partsOrLength: "4 parts",
    significance: "Co-written by Douglas Adams. Highest-rated classic Who episode.",
    blurb: "Paris. The Mona Lisa is a forgery. The villain is twelve people split across all of human history.", iconic: true },
  { title: "Logopolis", doctor: "4", year: 1981, format: "serial", partsOrLength: "4 parts",
    monsters: ["The Master / Missy"],
    significance: "Tom Baker's regeneration.",
    blurb: "Maths holds the universe together. The Master interrupts a calculation. Stars start to go out.", iconic: false },

  // ─── Davison ───
  { title: "Earthshock", doctor: "5", year: 1982, format: "serial", partsOrLength: "4 parts",
    monsters: ["Cybermen"],
    companions: ["Adric"],
    significance: "Cybermen return after seven years. Adric dies. Credits run in silence.",
    blurb: "Cyber-freighter slingshots back through time and Adric stays on board.", iconic: true },
  { title: "The Caves of Androzani", doctor: "5", year: 1984, format: "serial", partsOrLength: "4 parts",
    companions: ["Peri Brown"],
    significance: "Davison's regeneration. Often voted #1 classic Who episode of all time.",
    blurb: "Spectrox poisoning, gunrunners, magma beast. The Doctor dies of poisoning he chose for Peri.", iconic: true },

  // ─── Colin Baker ───
  { title: "Vengeance on Varos", doctor: "6", year: 1985, format: "serial", partsOrLength: "2 parts",
    significance: "Reality-TV satire 15 years before reality TV.",
    blurb: "Citizens vote on the torture of political prisoners. The Doctor walks into the broadcast.", iconic: false },

  // ─── McCoy ───
  { title: "Remembrance of the Daleks", doctor: "7", year: 1988, format: "serial", partsOrLength: "4 parts",
    monsters: ["Daleks"],
    companions: ["Ace"],
    significance: "Coal Hill 1963. Ace destroys a Dalek with a baseball bat.",
    blurb: "Two Dalek factions fight over the Hand of Omega. The Doctor planted it there 25 years earlier.", iconic: true },
  { title: "The Curse of Fenric", doctor: "7", year: 1989, format: "serial", partsOrLength: "4 parts",
    companions: ["Ace"],
    significance: "Peak Cartmel Masterplan. Ace gets a proper backstory.",
    blurb: "WW2 codebreakers, vampires from the future, a curse going back to the Norse. \"We play the contest again, Time Lord.\"", iconic: false },
  { title: "Survival", doctor: "7", year: 1989, format: "serial", partsOrLength: "3 parts",
    monsters: ["The Master / Missy"],
    companions: ["Ace"],
    significance: "Last classic-era serial. Ends with the Doctor's voice over a sunset.",
    blurb: "Cheetah-people transform humans on a dying planet. Perivale, otherwise.", iconic: false },

  // ─── McGann ───
  { title: "Doctor Who (The TV Movie)", doctor: "8", year: 1996, format: "special", partsOrLength: "85 min",
    companions: ["Grace Holloway"],
    significance: "Paul McGann's one TV outing.",
    blurb: "San Francisco, New Year's Eve 1999. The Master is a snake; the Doctor is half-human (allegedly).", iconic: false },
  { title: "The Night of the Doctor", doctor: "8", year: 2013, format: "minisode", partsOrLength: "7 min",
    significance: "McGann returns for seven minutes; turns the War Doctor canon.",
    blurb: "Eight refuses to choose, then chooses. \"Charley. C'rizz. Lucie. Tamsin. Molly. Friends, companions I've known — I salute you. And Cass… I apologise.\"", iconic: true },

  // ─── Eccleston ───
  { title: "Rose", doctor: "9", year: 2005, format: "episode", partsOrLength: "45 min",
    monsters: [],
    companions: ["Rose Tyler", "Mickey Smith"],
    significance: "The show comes back. RTD's reboot. 10 million viewers.",
    blurb: "Plastic dummies kill. The Doctor blows up Henrik's department store. \"Run.\"", iconic: true },
  { title: "Dalek", doctor: "9", year: 2005, format: "episode", partsOrLength: "45 min",
    monsters: ["Daleks"],
    companions: ["Rose Tyler"],
    significance: "Single Dalek in a basement. Nine breaks.",
    blurb: "Utah, 2012. Henry van Statten's alien museum. One Dalek wakes up.", iconic: true },
  { title: "The Empty Child / The Doctor Dances", doctor: "9", year: 2005, format: "episode", partsOrLength: "2 × 45 min",
    companions: ["Rose Tyler", "Captain Jack Harkness"],
    significance: "\"Are you my mummy?\" Steven Moffat's first script.",
    blurb: "Blitz London. A child in a gas mask asks the same question. Captain Jack walks on screen.", iconic: true },
  { title: "The Parting of the Ways", doctor: "9", year: 2005, format: "episode", partsOrLength: "45 min",
    monsters: ["Daleks"],
    companions: ["Rose Tyler", "Captain Jack Harkness"],
    significance: "Eccleston's regeneration. Bad Wolf reveal.",
    blurb: "Rose looks into the heart of the TARDIS. \"I want you safe, my Doctor.\"", iconic: true },

  // ─── Tennant 10 ───
  { title: "The Christmas Invasion", doctor: "10", year: 2005, format: "special", partsOrLength: "60 min",
    companions: ["Rose Tyler"],
    significance: "Tennant's first proper episode.",
    blurb: "Sycorax overhead. Tennant in pajamas with a satsuma. \"No second chances. I'm that sort of a man.\"", iconic: false },
  { title: "School Reunion", doctor: "10", year: 2006, format: "episode",
    companions: ["Rose Tyler", "Sarah Jane Smith"],
    significance: "Sarah Jane returns. Sets up her spin-off.",
    blurb: "K-9. \"Oh, you can talk!\" \"Affirmative.\"", iconic: true },
  { title: "The Girl in the Fireplace", doctor: "10", year: 2006, format: "episode",
    significance: "Steven Moffat one-shot. Madame de Pompadour and the clockwork droids.",
    blurb: "A 51st-century spaceship has time windows into 18th-century France. The Doctor stays one heartbeat too long.", iconic: true },
  { title: "Doomsday", doctor: "10", year: 2006, format: "episode",
    monsters: ["Daleks", "Cybermen"],
    companions: ["Rose Tyler"],
    significance: "Daleks vs Cybermen. Rose says goodbye on Bad Wolf Bay.",
    blurb: "Genesis Ark, void stuff, parallel-world wall. \"Rose Tyler—\"", iconic: true },
  { title: "Blink", doctor: "10", year: 2007, format: "episode",
    monsters: ["Weeping Angels"],
    significance: "Weeping Angels debut. The Doctor barely in his own episode.",
    blurb: "Sally Sparrow finds a message under wallpaper, dated 1969. Don't blink. Don't even blink.", iconic: true },
  { title: "Human Nature / The Family of Blood", doctor: "10", year: 2007, format: "episode", partsOrLength: "2 × 45 min",
    monsters: ["The Family of Blood"],
    companions: ["Martha Jones"],
    significance: "The Doctor hides as a human and forgets.",
    blurb: "1913 boys' school. John Smith falls in love. Martha works in the kitchens. The pocket watch ticks.", iconic: true },
  { title: "Utopia / The Sound of Drums / Last of the Time Lords", doctor: "10", year: 2007, format: "episode", partsOrLength: "3 × 45 min",
    monsters: ["The Master / Missy", "The Toclafane"],
    companions: ["Martha Jones", "Captain Jack Harkness"],
    significance: "Master returns. Year That Never Was.",
    blurb: "End of the universe, Utopia. Professor Yana opens his fob watch.", iconic: true },
  { title: "Silence in the Library / Forest of the Dead", doctor: "10", year: 2008, format: "episode", partsOrLength: "2 × 45 min",
    monsters: ["Vashta Nerada"],
    companions: ["River Song"],
    significance: "First appearance of River Song. Her ending, his beginning.",
    blurb: "The Library, planet-sized, empty. \"Hey. Who turned out the lights?\"", iconic: true },
  { title: "Midnight", doctor: "10", year: 2008, format: "episode",
    monsters: ["The Midnight Entity"],
    significance: "Cheap episode forced by budget cuts; one of the best.",
    blurb: "A pleasure shuttle on a planet bathed in lethal Xtonic light. Something knocks. The voices start.", iconic: true },
  { title: "Turn Left", doctor: "10", year: 2008, format: "episode",
    monsters: ["The Trickster"],
    companions: ["Donna Noble", "Rose Tyler"],
    significance: "What if Donna had turned right? Rose returns.",
    blurb: "The Doctor dies under the Thames. Britain becomes a refugee state. A beetle on Donna's back.", iconic: true },
  { title: "The Stolen Earth / Journey's End", doctor: "10", year: 2008, format: "episode", partsOrLength: "2 × 45 min",
    monsters: ["Daleks", "Davros"],
    companions: ["Donna Noble", "Rose Tyler", "Sarah Jane Smith", "Captain Jack Harkness", "Martha Jones", "Mickey Smith"],
    significance: "Every modern companion in one room. DoctorDonna.",
    blurb: "Earth stolen. Bees gone. Daleks back. Doctor regenerates into himself.", iconic: true },
  { title: "The End of Time", doctor: "10", year: 2009, format: "special", partsOrLength: "2 × 75 min",
    monsters: ["The Master / Missy"],
    companions: ["Wilfred Mott"],
    significance: "Tennant's regeneration. Four knocks.",
    blurb: "Master comes back as gold-eyed lightning. Rassilon returns. Wilf in the booth. \"I don't want to go.\"", iconic: true },

  // ─── Smith ───
  { title: "The Eleventh Hour", doctor: "11", year: 2010, format: "episode", partsOrLength: "65 min",
    companions: ["Amy Pond"],
    significance: "Matt Smith's debut.",
    blurb: "Fish fingers and custard. Twelve years late through Amelia's garden.", iconic: true },
  { title: "Vincent and the Doctor", doctor: "11", year: 2010, format: "episode",
    companions: ["Amy Pond"],
    significance: "Tony Curran as Vincent van Gogh.",
    blurb: "The Doctor takes a depressed man to a museum to see what he became. Still makes adults cry.", iconic: true },
  { title: "The Pandorica Opens / The Big Bang", doctor: "11", year: 2010, format: "episode", partsOrLength: "2 × 45 min",
    companions: ["Amy Pond", "Rory Williams", "River Song"],
    significance: "Series 5 finale. The Pandorica is built for the Doctor.",
    blurb: "Stonehenge. Roman legions. Every Doctor Who villain in one alliance. \"I am the Doctor.\"", iconic: true },
  { title: "The Doctor's Wife", doctor: "11", year: 2011, format: "episode",
    companions: ["Amy Pond", "Rory Williams"],
    significance: "Neil Gaiman script. The TARDIS speaks.",
    blurb: "House traps the TARDIS soul in a human body called Idris. \"Hello, Doctor. It's so very, very nice to meet you.\"", iconic: true },
  { title: "A Good Man Goes to War", doctor: "11", year: 2011, format: "episode",
    monsters: ["Headless Monks", "The Silence"],
    companions: ["Amy Pond", "Rory Williams", "River Song"],
    significance: "Melody Pond reveal.",
    blurb: "Demon's Run. The Doctor calls in every favour. River whispers her name.", iconic: false },
  { title: "The Angels Take Manhattan", doctor: "11", year: 2012, format: "episode",
    monsters: ["Weeping Angels"],
    companions: ["Amy Pond", "Rory Williams", "River Song"],
    significance: "Goodbye Ponds.",
    blurb: "Angel grabs Rory and sends him to 1938. Amy goes after him. The grave reads \"Williams\".", iconic: true },
  { title: "The Day of the Doctor", doctor: "11", year: 2013, format: "special", partsOrLength: "75 min",
    monsters: ["Zygons", "Daleks"],
    companions: ["Clara Oswald"],
    significance: "50th anniversary. Three Doctors. War Doctor canonised. Gallifrey saved.",
    blurb: "\"No sir. All thirteen!\"", iconic: true },
  { title: "The Time of the Doctor", doctor: "11", year: 2013, format: "special", partsOrLength: "60 min",
    monsters: ["Daleks", "Cybermen", "Weeping Angels", "The Silence"],
    significance: "Eleven's regeneration. Trenzalore. New regeneration cycle.",
    blurb: "Three centuries defending Christmas. \"I will always remember when the Doctor was me.\"", iconic: false },

  // ─── Capaldi ───
  { title: "Listen", doctor: "12", year: 2014, format: "episode",
    companions: ["Clara Oswald"],
    significance: "Moffat's best psychological one. Or scariest. Same thing.",
    blurb: "What if there's something under every bed and every shadow? Clara goes into the Doctor's childhood.", iconic: true },
  { title: "Heaven Sent", doctor: "12", year: 2015, format: "episode",
    significance: "Capaldi solo. 55 minutes inside the confession dial. 4.5 billion years.",
    blurb: "Bird in the mountain. The Doctor punches through.", iconic: true },
  { title: "Hell Bent", doctor: "12", year: 2015, format: "episode",
    companions: ["Clara Oswald"],
    significance: "Gallifrey returns. Clara escapes.",
    blurb: "The Doctor at the diner. \"Who's Clara?\"", iconic: false },
  { title: "Heaven Sent / Hell Bent / Face the Raven", doctor: "12", year: 2015, format: "episode", partsOrLength: "3 × 45 min",
    significance: "Series 9 finale trilogy. Clara dies, then escapes.",
    blurb: "Trap Street. Quantum Shade. \"Let me be brave.\"", iconic: false },
  { title: "World Enough and Time / The Doctor Falls", doctor: "12", year: 2017, format: "episode", partsOrLength: "2 × 50 min",
    monsters: ["Cybermen", "The Master / Missy"],
    companions: ["Bill Potts", "Nardole"],
    significance: "Mondasian Cybermen origin. Missy and Master duel.",
    blurb: "Mondasian colony ship near a black hole. Bill is converted. Both Masters die on the same battlefield.", iconic: true },
  { title: "Twice Upon a Time", doctor: "12", year: 2017, format: "special",
    companions: ["Bill Potts"],
    significance: "Capaldi's regeneration. First Doctor cameo (David Bradley).",
    blurb: "Two Doctors refuse to regenerate. \"Doctor — I let you go.\"", iconic: false },

  // ─── Whittaker ───
  { title: "The Woman Who Fell to Earth", doctor: "13", year: 2018, format: "episode", partsOrLength: "65 min",
    companions: ["Yasmin Khan", "Ryan Sinclair", "Graham O'Brien"],
    significance: "Jodie Whittaker's debut.",
    blurb: "Sheffield. Tooth-faced alien. The Doctor builds her own sonic.", iconic: true },
  { title: "Demons of the Punjab", doctor: "13", year: 2018, format: "episode",
    significance: "Partition of India, 1947. Yaz's grandmother.",
    blurb: "Witness aliens. A wedding. A border about to be drawn.", iconic: false },
  { title: "Spyfall", doctor: "13", year: 2020, format: "episode", partsOrLength: "2 parts",
    monsters: ["The Master / Missy"],
    significance: "Sacha Dhawan's Master debut. Gallifrey destroyed (again).",
    blurb: "Bond pastiche turns into Hidden Folk. \"Everything you think you know is a lie.\"", iconic: false },
  { title: "Fugitive of the Judoon", doctor: "13", year: 2020, format: "episode",
    significance: "Jo Martin's Fugitive Doctor. Canon explodes.",
    blurb: "Judoon platoon on the moon. Ruth Clayton hits a buried lever. A TARDIS is under the lighthouse.", iconic: true },
  { title: "The Timeless Children", doctor: "13", year: 2020, format: "episode",
    monsters: ["Cybermen", "The Master / Missy"],
    significance: "Timeless Child reveal. Doctor predates Gallifrey.",
    blurb: "Master burns Gallifrey, opens the Division's archives. The Doctor isn't who she thought.", iconic: true },
  { title: "Flux", doctor: "13", year: 2021, format: "serial", partsOrLength: "6 parts",
    monsters: ["The Ravagers / Swarm and Azure", "Daleks", "Cybermen", "Sontarans"],
    significance: "Six-part serial. The Flux unmakes the universe.",
    blurb: "Time itself splits open. The Division surfaces. Bel and Vinder cross continents.", iconic: false },
  { title: "The Power of the Doctor", doctor: "13", year: 2022, format: "special", partsOrLength: "90 min",
    monsters: ["Daleks", "Cybermen", "The Master / Missy"],
    companions: ["Yasmin Khan", "Tegan Jovanka", "Ace", "Jo Grant", "Mel Bush"],
    significance: "Whittaker's regeneration. Classic companions return. Bigeneration set up.",
    blurb: "Master in a Rasputin wig. \"I'm a goddess!\" Tennant's face appears.", iconic: true },

  // ─── Tennant 14 ───
  { title: "The Star Beast", doctor: "14", year: 2023, format: "special",
    companions: ["Donna Noble", "Wilfred Mott"],
    significance: "Tennant returns. Meep. DoctorDonna problem.",
    blurb: "An asteroid in Camden Town. \"Mother of mine\".", iconic: false },
  { title: "Wild Blue Yonder", doctor: "14", year: 2023, format: "special",
    significance: "Two-hander on the edge of the universe.",
    blurb: "Not-things. The TARDIS gone. Wilfred at the end of a phone line.", iconic: true },
  { title: "The Giggle", doctor: "14", year: 2023, format: "special",
    monsters: ["The Toymaker"],
    significance: "Bigeneration. Two Doctors at once.",
    blurb: "Toymaker tossed; Doctor split. \"Allons-y, geronimo, fan-cakes, whatever.\"", iconic: true },

  // ─── Gatwa ───
  { title: "The Church on Ruby Road", doctor: "15", year: 2023, format: "special",
    companions: ["Ruby Sunday"],
    significance: "Gatwa's first proper episode.",
    blurb: "Christmas Eve. Goblins. A baby on the church steps.", iconic: true },
  { title: "The Devil's Chord", doctor: "15", year: 2024, format: "episode",
    monsters: ["Maestro"],
    companions: ["Ruby Sunday"],
    significance: "1963 Abbey Road. Music returns to the world.",
    blurb: "The Beatles can't play. A chord that no one has ever heard fixes it.", iconic: true },
  { title: "Boom", doctor: "15", year: 2024, format: "episode",
    companions: ["Ruby Sunday"],
    significance: "Moffat returns. Doctor stands on a landmine.",
    blurb: "Algorithmic war. Vicar with a tablet. Forty-five minutes of \"don't move.\"", iconic: true },
  { title: "Empire of Death", doctor: "15", year: 2024, format: "episode",
    monsters: ["Sutekh"],
    companions: ["Ruby Sunday"],
    significance: "Sutekh returns after 49 years. Has been on the TARDIS the whole time.",
    blurb: "A whisper at the end of the universe. \"You will tell me her name.\"", iconic: true },
  { title: "The Robot Revolution", doctor: "15", year: 2025, format: "episode",
    companions: ["Belinda Chandra"],
    significance: "Belinda debut.",
    blurb: "An interstellar marketing star deed turns into a robot revolution.", iconic: false },
  { title: "Lux", doctor: "15", year: 2025, format: "episode",
    monsters: [],
    companions: ["Belinda Chandra"],
    significance: "Mr Ring-a-Ding. Animated villain.",
    blurb: "1952 Miami picture-house. The villain steps off the screen.", iconic: false },
];

export const episodesByYear = (() => {
  const m = new Map<number, Episode[]>();
  for (const e of episodes) {
    if (!m.has(e.year)) m.set(e.year, []);
    m.get(e.year)!.push(e);
  }
  return [...m.entries()].sort(([a], [b]) => a - b);
})();
